import { fontFamily } from 'tailwindcss/defaultTheme'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Noto Sans KR', fontFamily.sans],
      },
      fontSize: {
        '28_bold': [
          '28px',
          {
            fontWeight: '700',
            lineHeight: '150%',
            letterSpacing: '2%',
          },
        ],
        '24_bold': [
          '24px',
          {
            fontWeight: '700',
            lineHeight: '150%',
            letterSpacing: '2%',
          },
        ],
        '24_medium': [
          '24px',
          {
            fontWeight: '500',
            lineHeight: '150%',
            letterSpacing: '2%',
          },
        ],
        '22_medium': [
          '22px',
          {
            fontWeight: '500',
            lineHeight: '150%',
            letterSpacing: '2%',
          },
        ],
        '20_medium': [
          '20px',
          {
            fontWeight: '500',
            lineHeight: '150%',
            letterSpacing: '2%',
          },
        ],
        '18_medium': [
          '18px',
          {
            fontWeight: '500',
            lineHeight: '150%',
            letterSpacing: '2%',
          },
        ],
      },
      colors: {
        background: {
          DEFAULT: 'hsl(var(--background-50))',
          50: 'hsl(var(--background-50))',
          900: 'hsl(var(--background-900))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary-500))',
          50: 'hsl(var(--primary-50))',
          100: 'hsl(var(--primary-100))',
          200: 'hsl(var(--primary-200))',
          300: 'hsl(var(--primary-300))',
          400: 'hsl(var(--primary-400))',
          500: 'hsl(var(--primary-500))',
          600: 'hsl(var(--primary-600))',
          700: 'hsl(var(--primary-700))',
          800: 'hsl(var(--primary-800))',
          900: 'hsl(var(--primary-900))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary-500))',
          50: 'hsl(var(--secondary-50))',
          100: 'hsl(var(--secondary-100))',
          200: 'hsl(var(--secondary-200))',
          300: 'hsl(var(--secondary-300))',
          400: 'hsl(var(--secondary-400))',
          500: 'hsl(var(--secondary-500))',
          600: 'hsl(var(--secondary-600))',
          700: 'hsl(var(--secondary-700))',
          800: 'hsl(var(--secondary-800))',
          900: 'hsl(var(--secondary-900))',
        },
        error: {
          DEFAULT: 'hsl(var(--error-500))',
          50: 'hsl(var(--error-50))',
          100: 'hsl(var(--error-100))',
          200: 'hsl(var(--error-200))',
          300: 'hsl(var(--error-300))',
          400: 'hsl(var(--error-400))',
          500: 'hsl(var(--error-500))',
          600: 'hsl(var(--error-600))',
          700: 'hsl(var(--error-700))',
          800: 'hsl(var(--error-800))',
          900: 'hsl(var(--error-900))',
        },
        success: {
          DEFAULT: 'hsl(var(--success-500))',
          50: 'hsl(var(--success-50))',
          100: 'hsl(var(--success-100))',
          200: 'hsl(var(--success-200))',
          300: 'hsl(var(--success-300))',
          400: 'hsl(var(--success-400))',
          500: 'hsl(var(--success-500))',
          600: 'hsl(var(--success-600))',
          700: 'hsl(var(--success-700))',
          800: 'hsl(var(--success-800))',
          900: 'hsl(var(--success-900))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning-500))',
          50: 'hsl(var(--warning-50))',
          100: 'hsl(var(--warning-100))',
          200: 'hsl(var(--warning-200))',
          300: 'hsl(var(--warning-300))',
          400: 'hsl(var(--warning-400))',
          500: 'hsl(var(--warning-500))',
          600: 'hsl(var(--warning-600))',
          700: 'hsl(var(--warning-700))',
          800: 'hsl(var(--warning-800))',
          900: 'hsl(var(--warning-900))',
        },
        info: {
          DEFAULT: 'hsl(var(--info-500))',
          50: 'hsl(var(--info-50))',
          100: 'hsl(var(--info-100))',
          200: 'hsl(var(--info-200))',
          300: 'hsl(var(--info-300))',
          400: 'hsl(var(--info-400))',
          500: 'hsl(var(--info-500))',
          600: 'hsl(var(--info-600))',
          700: 'hsl(var(--info-700))',
          800: 'hsl(var(--info-800))',
          900: 'hsl(var(--info-900))',
        },
        gray: {
          DEFAULT: 'hsl(var(--gray-500))',
          50: 'hsl(var(--gray-50))',
          100: 'hsl(var(--gray-100))',
          200: 'hsl(var(--gray-200))',
          300: 'hsl(var(--gray-300))',
          400: 'hsl(var(--gray-400))',
          500: 'hsl(var(--gray-500))',
          600: 'hsl(var(--gray-600))',
          700: 'hsl(var(--gray-700))',
          800: 'hsl(var(--gray-800))',
          900: 'hsl(var(--gray-900))',
        },
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        xl: 'calc(var(--radius) * 9999)',
        lg: 'calc(var(--radius) * 2)',
        md: 'var(--radius)',
        sm: 'calc(var(--radius) / 2)',
        xs: 'calc(var(--radius) / 4)',
      },
    },
  },
  plugins: [],
}
